version: '3'
services:
  web:
    image: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/group-s3p-backendserver:latest
    ports:
      - "8111:8111"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reskill_group_sps
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web