version: '3.7'
services:
  dynamodb:
    container_name: dynamodb_docker
    image: "${DB_IMAGE}"
    ports:
      - '8000:8000'
  s3p-app:
    container_name: s3p_backend
    image: "${BACKEND_IMAGE}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - NO_NEED_FOR_THIS=but still included to show a concept
    env_file:
      - "${ENV_FILE}"
    ports:
      - "8111:${SERVER_PORT}"