package no.dnb.reskill.ec_webserver.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@NoArgsConstructor
@DynamoDBTable(tableName = "Configuration")
public class Configuration {
    private Long id;
    private String key_name;
    private String value;
    private LocalDateTime timestamp_added;
    private LocalDateTime timestamp_modified;
    private Long userId;
    private Long environmentId;

    public Configuration(Long id, String key_name, String value, Long userId, Long environmentId) {
        this.id = id;
        this.key_name = key_name;
        this.value = value;
        this.userId = userId;
        this.environmentId = environmentId;
    }

    // TODO: DynamoDB - only strings can be autogenerated???
    @DynamoDBHashKey(attributeName="id")
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    @DynamoDBAttribute
    public String getKey_name() {
        return key_name;
    }
    public void setKey_name(String key_name) {
        this.key_name = key_name;
    }

    @DynamoDBAttribute
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        this.value = value;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    public LocalDateTime getTimestamp_added() {
        return timestamp_added;
    }
    public void setTimestamp_added(LocalDateTime timestamp_added) {
        this.timestamp_added = timestamp_added;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    public LocalDateTime getTimestamp_modified() {
        return timestamp_modified;
    }
    public void setTimestamp_modified(LocalDateTime timestamp_modified) {
        this.timestamp_modified = timestamp_modified;
    }

    @DynamoDBAttribute
    public Long getUserId() {
        return userId;
    }
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public Long getEnvironmentId() {
        return environmentId;
    }
    public void setEnvironmentId(Long environmentId) {
        this.environmentId = environmentId;
    }



    /*
    Dummies to be able to test
     */

    public void setEnvironment(Environment e) {
        environmentId = e.getId();
    }

    public Environment getEnvironment() {
        return null;
    }


}
