package no.dnb.reskill.ec_webserver.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDateTime;
import java.util.Date;

//
//@Data
//@NoArgsConstructor
//@DynamoDBTable(tableName = "Configuration")
//public class Configuration {
//    @DynamoDBHashKey(attributeName="id")
//    @DynamoDBAutoGeneratedKey
//    private String id;
//    @DynamoDBAttribute
//    private String key_name;
//    @DynamoDBAttribute
//    private String value;
//    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
//    private Date timestamp_added;
//    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
//    private Date timestamp_modified;
//    @DynamoDBAttribute
//    private String userId;
//    @DynamoDBAttribute
//    private String environmentId;
//
//    public Configuration(String id, String key_name, String value, String userId, String environmentId) {
//        this.id = id;
//        this.key_name = key_name;
//        this.value = value;
//        this.userId = userId;
//        this.environmentId = environmentId;
//    }
//
//    /*
//    Dummies to be able to test
//     */
//    public void setEnvironment(Environment e) {
//        environmentId = e.getId();
//    }
//    public Environment getEnvironment() {
//        return null;
//    }
//
//    public String getUserId() {
//        return userId;
//    }
//    public void setUserId(String userId) {
//        this.userId = userId;
//    }
//}


@DynamoDBTable(tableName = "Configuration")
public class Configuration {
    private String id;
    private String key_name;
    private String value;
    private Date timestamp_added;
    private Date timestamp_modified;
    private String userId;
    private String environmentId;

    public Configuration(String id, String key_name, String value, String userId, String environmentId) {
        this.id = id;
        this.key_name = key_name;
        this.value = value;
        this.userId = userId;
        this.environmentId = environmentId;
    }

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute
    public String getKey_name() {
        return key_name;
    }
    public void setKey_name(String key_name) {
        this.key_name = key_name;
    }

    @DynamoDBAttribute
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        this.value = value;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    public Date getTimestamp_added() {
        return timestamp_added;
    }
    public void setTimestamp_added(Date timestamp_added) {
        this.timestamp_added = timestamp_added;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getTimestamp_modified() {
        return timestamp_modified;
    }
    public void setTimestamp_modified(Date timestamp_modified) {
        this.timestamp_modified = timestamp_modified;
    }

    @DynamoDBAttribute
    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getEnvironmentId() {
        return environmentId;
    }
    public void setEnvironmentId(String environmentId) {
        this.environmentId = environmentId;
    }



    /*
    Dummies to be able to test
     */

    public void setEnvironment(Environment e) {
        environmentId = e.getId();
    }

    public Environment getEnvironment() {
        return null;
    }


}
