package no.dnb.reskill.ec_webserver.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;


@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "Configuration")
public class Configuration {
    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String key_name;
    @DynamoDBAttribute
    private String value;
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date timestamp_added;
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date timestamp_modified;
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String environmentId;

    public Configuration(String id, String environmentId, String key_name, String value, String userId) {
        this.id = id;
        this.environmentId = environmentId;
        this.key_name = key_name;
        this.value = value;
        this.userId = userId;

    }

    /*
    Dummies to be able to test
     */
    @DynamoDBIgnore
    public void setEnvironment(Environment e) {
        environmentId = e.getId();
    }
//    @DynamoDBIgnore
//    public Environment getEnvironment() {
//
//        return null;
//    }

}

